Feat/add landing page
getevoize/evoize-landing pull request #2
Opened 2024-10-09 17:22 UTC by elbbo

First draft for the landing page. It only includes the structure. Content and animations will be added in a following branch.

2024-10-09 18:15 UTC, lowbits commented on app.vue
> +					secondary-color="#f5d0fe"
Maybe would make sense to add an array

```vue
const content = [{content: {}, color: '', }]

...

<PreviewCard v-for="card in contentCards" :content="card.content" />

```

2024-10-09 18:15 UTC, lowbits commented on app.vue
> +			/>
same as above

2024-10-09 18:15 UTC, lowbits commented on app.vue
> +	value2: '38.000€',
would be more prescise by naming the variables

maybe `totalRequired` `currentAmount` or `total` and `current`

2024-10-09 18:15 UTC, lowbits commented on components/FeatureHighlight.vue
> +			class="rounded-[3rem] border-4 border-[#95BAFC] border-opacity-20"
Is it an option here to create new own rounded corner class? rounded-something.

2024-10-09 18:15 UTC, lowbits commented on components/FeatureHighlight.vue
> +})
I think its better here to use the ts version

```ts
defineProps<{imageSrc: string, ...}>() 
```

2024-10-09 18:15 UTC, lowbits commented on components/SectionTitle.vue
> +})
```ts
withDefaults(defineProps<{
title: string,
color: string,
align: 'left' | 'center' | 'right'
}>)({align: 'left'})
``

2024-10-23 17:30 UTC, Eddy401 requested changes
Finished my review. All in all functional. Used this review to get used to Vue. There are some things in the code that are not ideal from my point of view, but I understand the simplicity of this page which lowers the treshold to gold plating a lot.

I think my technical point are not too important. Which is important to me is naming. Please ensure we have a easy to understand, striking and consistent naming convention across the landing page.

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +	<div class="relative bg-gradient-to-t from-[#DBF1FE] to-[#FFFFFF]">
Should we add those colors into a theme?

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +			<PageTeaser />
Suggestion: Rename to `HeroSection`

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +		<HeaderBackground />
Suggestion: Rename to `HeroBackground`

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +		secondaryColor: '#fdf4e5',
Can we pull these values from a theme file too? Asking to allow theme related changes in one place.

2024-10-23 17:30 UTC, Eddy401 commented on components/AppNavigation.vue
> +<template>
Question: Why are all components using the template type? Looking at the definition this type is not suitable for the use cases we use it for.

2024-10-23 17:30 UTC, Eddy401 commented on components/HeaderBackground.vue
> +</script>
Question: Is this required?

2024-10-23 17:30 UTC, Eddy401 commented on components/HeaderBackground.vue
> +<!--  <div class="top-[8%] right-[40%] bg-shape-1 bg-blue-300 opacity-50 blur-3xl overflow-hidden "></div> -->
Polish: Unused code?

2024-10-23 17:30 UTC, Eddy401 commented on components/HeaderBackground.vue
> +</style>
Polish: Unused code?

2024-10-23 17:30 UTC, Eddy401 commented on components/PreviewCard.vue
> +}>()
Question: Why can't this type be exported like this?
```suggestion
defineProps<PreviewCardProps>()
```

2024-10-23 17:30 UTC, Eddy401 commented on components/PreviewCard.vue
> +export interface PreviewCardProps {
Nitpick: I think this `export` is not required here, because we export via `defineProps`.

```suggestion
interface PreviewCardProps {
```

2024-10-23 17:30 UTC, Eddy401 commented on components/SectionTitle.vue
> +	color: string
Polish: unused

2024-10-23 17:30 UTC, Eddy401 commented on components/FeatureHighlight.vue
> +	eyebrow: string
Chore: Eyebrow is a strange term. I suggest to use `caption` to describe the type of text understandable for everyone.

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +			<FeatureHighlight
Suggestion: Rename to content card. This design is not only limited to highlight Features

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +				:reverse="highlight.reverse"
Question: Do those properties have to be passed explicitly? Can't we just pass the whole `highlight` object?

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +		<PromoSection />
Praise: I like the split of the landing page into sections. I would extends this approach too the other sections too. 

Suggestion: Place Section Components into a "sections" folder

2024-10-23 17:30 UTC, Eddy401 commented on components/PromoSection.vue
> +		</div>
Thought: This is another type of content card. Maybe we can combine all type into one Abstract ContentCard Type that we can assign a type to.

2024-10-23 17:30 UTC, Eddy401 commented on app.vue
> +		<PricingSection
Suggestion: Can that Section have a more generic name? This section also qualifies for other content representations.

2024-10-23 17:30 UTC, Eddy401 commented on components/PricingSection.vue
> +				<PricingCard
Suggestion: Can that Section have a more generic name? This section also qualifies for other content representations.

2024-10-23 17:30 UTC, Eddy401 commented on components/PricingSection.vue
> +		}>,
Todo: This entry should inherit its type from `PricingCard`

2024-10-23 17:30 UTC, Eddy401 commented on components/PricingCard.vue
> +})
Todo: This object is very pricing biased. No need to do so.

2024-10-23 19:45 UTC, elbbo commented on components/AppNavigation.vue
> +<template>
https://vuejs.org/api/built-in-special-elements#template

Single-file components use a [top-level <template> tag](https://vuejs.org/api/sfc-spec#language-blocks) to wrap the entire template. That usage is separate from the use of <template> described above. That top-level tag is not part of the template itself and doesn't support template syntax, such as directives.

2024-10-23 19:48 UTC, elbbo commented on app.vue
> +	<div class="relative bg-gradient-to-t from-[#DBF1FE] to-[#FFFFFF]">
I had thought about that too, but decided against it. I would store a color scheme in the configuration once we have one. At the moment, this is the only place where we are using this gradient, so I would leave it inline here for now.

2024-10-23 19:49 UTC, elbbo commented on app.vue
> +			<PageTeaser />
Sounds good. That sounds like a coherent naming convention.

2024-10-23 19:52 UTC, elbbo commented on app.vue
> +		secondaryColor: '#fdf4e5',
That mainly refers to the content cards, and the colors haven't appeared as prominently in our "color scheme" so far. I would actually prefer to keep them with the component for now, or how would you name them? Something like schema-content-highlight-main-500?

2024-10-30 18:38 UTC, Eddy401 approved these changes

2024-10-30 18:39 UTC, merged